.\"
.\" Copyright (c) 2019 Marcel Moolenaar
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE DEVELOPERS ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
.\" OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
.\" IN NO EVENT SHALL THE DEVELOPERS BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
.\" NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
.\" DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
.\" THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
.\" THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.\" $FreeBSD$
.\"
.Dd August 4, 2019
.Dt VDSK_DOES_TRIM 3
.Os
.Sh NAME
.Nm vdsk_does_trim
.Nd return whether a disk, disk partition or disk image file supports TRIM
.Sh LIBRARY
.Lb libvdsk
.Sh SYNOPSIS
.In vdsk.h
.Ft int
.Fn vdsk_does_trim "vdskctx vdsk"
.Sh DESCRIPTION
The
.Nm vdsk_does_trim
function returns whether the underlying disk or disk partition supports
the TRIM (aka UNMAP) command.
Normal programs do not need to know this, because the
.Nm vdsk_trim
function can always be used, even if the underlying disk or partition
does not support it.
This function is specifically provided for programs that have a need to
know this, such as virtual machine implementations.
.Sh SEE ALSO
.Xr libvdsk 3 ,
.Xr vdsk_open 3 ,
.Xr vdsk_trim 3
